<?php

namespace Container2E3l71x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFetchFreshMoviesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\FetchFreshMovies' shared autowired service.
     *
     * @return \App\Command\FetchFreshMovies
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\FetchFreshMovies'] = $instance = new \App\Command\FetchFreshMovies();

        $instance->setName('app:FetchFreshMovies');

        return $instance;
    }
}
