<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2E3l71x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2E3l71x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2E3l71x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2E3l71x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2E3l71x\App_KernelDevDebugContainer([
    'container.build_hash' => '2E3l71x',
    'container.build_id' => '587626ab',
    'container.build_time' => 1612908668,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2E3l71x');
